//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseCartReturnDetail
    {
        public int PurchaseCartReturnDetail { get; set; }
        public int ProductID { get; set; }
        public int PurchaseQuantity { get; set; }
        public double purchaseUnitPrice { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public int UserID { get; set; }
        public double PreviousPurchaseUnitPrice { get; set; }
        public string Description { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public double SaleUnitPrice { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblProductType tblProductType { get; set; }
        public virtual tblStock tblStock { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
