//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Transaction
    {
        public int TransactionID { get; set; }
        public int FinancialYearID { get; set; }
        public int AccountHeadID { get; set; }
        public int AccountControlID { get; set; }
        public int AccountSubControlID { get; set; }
        public string AccountTitle { get; set; }
        public string InvoiceNo { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public System.DateTime TransectionDate { get; set; }
        public string TransectionTitle { get; set; }
        public int UserID { get; set; }
    }
}
